name: Create the release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  create-release:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chyle
        run: |
          go install github.com/antham/chyle@latest

          FROM_TAG=$(git tag -l --sort=-v:refname|head -n 2|tail -n 1)
          TO_TAG=$(git tag -l --sort=-v:refname|head -n 1)
          export CHYLE_GIT_REPOSITORY_PATH="."
          export CHYLE_GIT_REFERENCE_FROM="$(git rev-parse $FROM_TAG)"
          export CHYLE_GIT_REFERENCE_TO="$(git rev-parse $TO_TAG)"
          export CHYLE_MATCHERS_TYPE="merge"
          export CHYLE_EXTRACTORS_GITHUBISSUEID_ORIGKEY="message"
          export CHYLE_EXTRACTORS_GITHUBISSUEID_DESTKEY="githubIssueId"
          export CHYLE_EXTRACTORS_GITHUBISSUEID_REG="#(\\d+)"
          export CHYLE_DECORATORS_GITHUBISSUE_CREDENTIALS_OWNER="antham"
          export CHYLE_DECORATORS_GITHUBISSUE_CREDENTIALS_OAUTHTOKEN="$GITHUB_TOKEN"
          export CHYLE_DECORATORS_GITHUBISSUE_KEYS_TITLE_DESTKEY="issueTitle"
          export CHYLE_DECORATORS_GITHUBISSUE_KEYS_TITLE_FIELD="title"
          export CHYLE_DECORATORS_GITHUBISSUE_REPOSITORY_NAME="$CIRCLE_PROJECT_REPONAME"
          export CHYLE_SENDERS_GITHUBRELEASE_CREDENTIALS_OAUTHTOKEN="$GITHUB_TOKEN"
          export CHYLE_SENDERS_GITHUBRELEASE_CREDENTIALS_OWNER="antham"
          export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_TAGNAME="$TO_TAG"
          export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_UPDATE="true"
          export CHYLE_SENDERS_GITHUBRELEASE_REPOSITORY_NAME="$CIRCLE_PROJECT_REPONAME"
          export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_TEMPLATE='### Changes
          {{ range $key, $value := .Datas }}
          => {{ $value.issueTitle }} (#{{ $value.githubIssueId }}) {{ end }}'
          chyle create
