name: Create the release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  create-release:
    name: Release binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install chyle
        run: go install github.com/antham/chyle@latest

      - name: Run chyle
        run: |
          FROM_TAG=$(git tag -l --sort=-v:refname|head -n 2|tail -n 1)
          TO_TAG=$(git tag -l --sort=-v:refname|head -n 1)
          REPOSITORY_NAME=$(basename "$GITHUB_REPOSITORY")

          export CHYLE_GIT_REFERENCE_FROM="$(git rev-parse $FROM_TAG)"
          export CHYLE_GIT_REFERENCE_TO="$(git rev-parse $TO_TAG)"
          export CHYLE_DECORATORS_GITHUBISSUE_REPOSITORY_NAME="$REPOSITORY_NAME"
          export CHYLE_SENDERS_GITHUBRELEASE_RELEASE_TAGNAME="$TO_TAG"
          export CHYLE_SENDERS_GITHUBRELEASE_REPOSITORY_NAME="$REPOSITORY_NAME"
          chyle create
        env:
          CHYLE_GIT_REPOSITORY_PATH: "."
          CHYLE_EXTRACTORS_GITHUBISSUEID_ORIGKEY: "message"
          CHYLE_EXTRACTORS_GITHUBISSUEID_DESTKEY: "githubIssueId"
          CHYLE_EXTRACTORS_GITHUBISSUEID_REG: "#(\\d+)"
          CHYLE_MATCHERS_TYPE: "merge"
          CHYLE_DECORATORS_GITHUBISSUE_CREDENTIALS_OWNER: ${{ github.repository_owner }}
          CHYLE_DECORATORS_GITHUBISSUE_CREDENTIALS_OAUTHTOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHYLE_DECORATORS_GITHUBISSUE_KEYS_TITLE_DESTKEY: "issueTitle"
          CHYLE_DECORATORS_GITHUBISSUE_KEYS_TITLE_FIELD: "title"
          CHYLE_SENDERS_GITHUBRELEASE_CREDENTIALS_OWNER: ${{ github.repository_owner }}
          CHYLE_SENDERS_GITHUBRELEASE_CREDENTIALS_OAUTHTOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHYLE_SENDERS_GITHUBRELEASE_RELEASE_UPDATE: "true"
          CHYLE_SENDERS_GITHUBRELEASE_RELEASE_TEMPLATE: |
            ### Changes
            {{ range $key, $value := .Datas }}
            => {{ $value.issueTitle }} (#{{ $value.githubIssueId }}) {{ end }}
